### ISSUE TITLE
Train model for a class not in COCO dataset

### ISSUE THREAD

**Issue by hussainfolio3** [tristanratz/Interactive-Image-Segmentation#1]
Hi, can I use the COCO pre-trained model for annotating a class that is not present in the COCO Dataset?

**Comment by tristanratz** [comment]
Hey,
yeah this is the purpose of this project. You have to manual label about 50-70 examples before training the model. After that the model should suggest predictions to you which you may have to alter to let them work properly.

After a while you can iteratively retrain the model to let it get more accurate.

**Comment by hussainfolio3** [comment]
I am getting this error


Project loading error
__init__() missing 1 required positional argument: 'project_dir'
Traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/label_studio/utils/misc.py", line 89, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/label_studio/server.py", line 150, in prepare_globals
    g.project = project_get_or_create()
  File "/usr/local/lib/python3.7/site-packages/label_studio/server.py", line 126, in project_get_or_create
    input_args, context={'multi_session': False})
  File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 889, in get_or_create
    project = cls.get(project_name, args, context)
  File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 872, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 860, in _load_from_dir
    return cls(config, project_name, context=context, root_dir=args.root_dir)
  File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 91, in __init__
    self.load_converter()
  File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 241, in load_converter
    self.converter = Converter(self.parsed_label_config)
TypeError: __init__() missing 1 required positional argument: 'project_dir'
