### ISSUE TITLE
init() missing 1 required positional argument: 'project_dir'

### ISSUE THREAD

**Issue by hussainfolio3** [tristanratz/Interactive-Image-Segmentation#2]
I am getting this error

```
Project loading error
init() missing 1 required positional argument: 'project_dir'
Traceback
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/label_studio/utils/misc.py", line 89, in exception_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/label_studio/server.py", line 150, in prepare_globals
g.project = project_get_or_create()
File "/usr/local/lib/python3.7/site-packages/label_studio/server.py", line 126, in project_get_or_create
input_args, context={'multi_session': False})
File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 889, in get_or_create
project = cls.get(project_name, args, context)
File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 872, in get
project = cls._load_from_dir(project_dir, project_name, args, context)
File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 860, in _load_from_dir
return cls(config, project_name, context=context, root_dir=args.root_dir)
File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 91, in init
self.load_converter()
File "/usr/local/lib/python3.7/site-packages/label_studio/project.py", line 241, in load_converter
self.converter = Converter(self.parsed_label_config)
TypeError: init() missing 1 required positional argument: 'project_dir'
```

**Comment by kodecreer** [comment]
I got the same issue as well

**Comment by auser** [comment]
> I got the same issue as well

Did you ever fix it?
